language: cpp
compiler:
  - gcc
  - clang

env:
  - CONFIG=Debug COVERAGE=0 
  - CONFIG=Debug COVERAGE=1 DOC=1
  - CONFIG=Release COVERAGE=0

matrix:
  exclude:
    - compiler: clang
      env: CONFIG=Debug COVERAGE=1 DOC=1
    - compiler: gcc
      env: CONFIG=Debug COVERAGE=0  

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - estermann.michel@gmail.com
    on_success: change
    on_failure: always


before_install:
  - if test ${CC} = gcc ; then sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test ; fi
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
  - tar -zxvf cmake-3.2.3-Linux-x86_64.tar.gz
  - ln -s cmake-3.2.3-Linux-x86_64/bin/cmake cmake-3 
  - sudo apt-get -qq update 
  - if test ${CC} = gcc ; then sudo apt-get -y -qq install g++-4.8 ; fi
  - if test ${CC} = gcc ; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8 --slave /usr/bin/gcov gcov /usr/bin/gcov-4.8 ; fi
  - if test ${CC} = gcc ; then sudo update-alternatives --set gcc /usr/bin/gcc-4.8 ; fi
  - gem install cucumber
  - if [ "${COVERAGE}" = '1' ] ; then sudo pip install cpp-coveralls --use-mirrors; fi
  - if [ "${DOC}" = '1' ] ; then sudo apt-get -y -qq install doxygen graphviz; fi

before_script:
  - mkdir build && (cd build && ../cmake-3 -DCMAKE_BUILD_TYPE=$CONFIG ..) 
  - ./cmake-3 --build build --target external_dependencies --config $CONFIG

script:
  - ./cmake-3 --build build --target all --config $CONFIG
  - ./cmake-3 --build build --target run_feature_tests --config $CONFIG
  - ./cmake-3 --build build --target CMake_project_template --config $CONFIG
  - if [ "${COVERAGE}" = '1' ] ; then ./cmake-3 --build build --target coverage --config $CONFIG ; fi 
  - if [ "${DOC}" = '1' ] ; then ./cmake-3 --build build --target doc ; fi

after_success:
  - if [ "${COVERAGE}" = '1' ] ; then coveralls -E.*/externals/.* -E/usr/include/.* -E.*/tests/.* -E.*/CMakeFiles/.* ; fi
